### ISSUE TITLE
[vue-i18n-bridge 9.2.0-beta.39] custom block no longer works in Vue 2.6

### ISSUE THREAD

**Issue by kingyue737** [intlify/vue-i18n-next#1073]
### Reporting a bug?

Custom block now works in Vue 2.7 🎉🎉, but no longer works in Vue 2.6😭. Some new errors happen:

```
TypeError: Cannot read properties of undefined (reading '$options')
TypeError: _vm.t is not a function
```

### Expected behavior

No error

### Reproduction

https://stackblitz.com/edit/vitejs-vite-wk6hhj

Open the reproduction link and see the devtool terminal

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @intlify/unplugin-vue-i18n: ^0.4.0 => 0.4.0 
    @vue/composition-api: ^1.7.0 => 1.7.0 
    vite: ^3.0.0 => 3.0.0 
    vite-plugin-inspect: ^0.6.0 => 0.6.0 
    vite-plugin-vue2: ^2.0.2 => 2.0.2 
    vue: 2.6.14 => 2.6.14 
    vue-demi: ^0.13.5 => 0.13.5 
    vue-i18n: ^8.27.2 => 8.27.2 
    vue-i18n-bridge: 9.2.0-beta.39 => 9.2.0-beta.39 
    vue-template-babel-compiler: ^1.2.0 => 1.2.0 
    vue-template-compiler: 2.6.14 => 2.6.14
```

### Additional context

If it's an intended breaking change, we may need to indicate in the docs that the support of Vue 2.6 is dropped.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting as always!

OMG 😓 
We had to notice the `@vue/composition-api` proxy in Vue 2.6 and the behavior of Vue 2.7.
