### ISSUE TITLE
`i18n.global.locale` type definiton wrong

### ISSUE THREAD

**Issue by WangHansen** [intlify/vue-i18n-next#1003]
### Reporting a bug?

When I implemented a function to globally switch locale as follows:
<img width="409" alt="截屏2022-05-07 下午11 31 39" src="https://user-images.githubusercontent.com/15679461/167280563-b0d39325-3257-464e-88f2-d97002f7b75b.png">

The type definition for `i18n.global.locale` is wrong:
<img width="591" alt="截屏2022-05-07 下午11 32 31" src="https://user-images.githubusercontent.com/15679461/167280585-e5b1d0ff-83dc-4008-86b8-a9a595a9ba2e.png">

By printing out the console, I was able to see that `i18n.global.locale` should be a computed value

### Expected behavior

TypeScript not throw error

### Reproduction

Type definition problem

### System Info

```shell
System:
  OS: macOS 12.3.1
  CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Memory: 171.65 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 8.6.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Watchman: 2021.10.18.00 - /usr/local/bin/watchman
Browsers:
  Brave Browser: 91.1.26.77
  Chrome: 101.0.4951.54
  Safari: 15.4

"vue": "^3.2.25",
"vue-i18n": "^9.1.10",
"@intlify/vite-plugin-vue-i18n": "^3.4.0",
"@vitejs/plugin-vue": "^2.3.1",
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

I seem that the i18n instance is created with `createI18n` with `legacy: true` option.

The `global` property can refer to Composer or VueI18n, as described in the API docs.
https://vue-i18n.intlify.dev/api/general.html#global

You can check the mode of an i18n instance with `mode`.
https://vue-i18n.intlify.dev/api/general.html#mode

**Comment by WangHansen** [comment]
> Thank you for your reporting!
> 
> I seem that the i18n instance is created with `createI18n` with `legacy: true` option.
> 
> The `global` property can refer to Composer or VueI18n, as described in the API docs. https://vue-i18n.intlify.dev/api/general.html#global
> 
> You can check the mode of an i18n instance with `mode`. https://vue-i18n.intlify.dev/api/general.html#mode

Sorry, should specify, I actually created with `legacy: false`:
```javascript
const i18n = createI18n<I18nOptions, [MessageSchema], 'zh-CN' | 'en-CA'>({
  legacy: false,
  locale: getLang(),
  messages: {
    'zh-CN': zhCN,
    'en-CA': enCA,
  },
  // something vue-i18n options here ...
});
```

**Comment by markbrockhoff** [comment]
Hi, I was facing the same problem on vue-i18n 9.2.0-beta.31.

I had a look at the type of i18n.global.locale and it's of type `string | WritableComputedRef`. So you can't access `.value` unless you tell Typescript that i18n.global.locale is not a string but a ref.
Therefore I just added a typeguard using the isRef function from vue:

```ts
export const changeLocale = (i18n: I18n, locale: string) => {
  if (i18n.mode === 'legacy') {
    i18n.global.locale = locale;
  } else if (isRef(i18n.global.locale)) {
    i18n.global.locale.value = locale;
  }
};
```

That way the type changes to Ref inside the else block.
But this behaviour should be documented as the example in the Documentation does currently not work for Typescript.

**Comment by leo-martin** [comment]
Hi I am facing the same issue.

I'm using i18n 9.1.10 (fixed version)

Here is my i18n setup
```
const i18n = createI18n({
  locale: 'fr',
  legacy: false,
  fallbackLocale: 'en',
  globalInjection: true,
  messages: messages as LocaleMessages<VueMessageType>,
})
```

In the same file, I try to access and modify the locale using `i18n.global.locale`.  When I check in my code, the type for `i18n.global.locale` is a ref but if I try `i18n.global.locale.value = 'fr'` then I get a console error saying i18n.global.locale is a String and if I log `i18n.global.locale.value` I get `undefined`

I've checked and I'm using the composition mode (i18n.mode is `composition`) . I've tried checking with isRef, and it always returns false even though mode is composition.


Any help is appreciated

**Comment by porkus1990** [comment]
Have the same problem with next-version. With `legacy: false` i have to set it with `i18n.global.locale.value = locale;`

**Comment by valgeirb** [comment]
I'm facing the same problem I think, getting an unknown type from `locale` which is causing errors with `v-model`:

<img width="723" alt="Screenshot 2022-08-05 at 10 21 41" src="https://user-images.githubusercontent.com/2593027/183057729-56b198e1-53cd-4b9d-b667-493077509548.png">

<img width="979" alt="Screenshot 2022-08-05 at 10 23 01" src="https://user-images.githubusercontent.com/2593027/183058020-a24b45f1-a1f2-4601-a70c-e29679c56160.png">

**Comment by timothymctim** [comment]
To me it’s clear that this bug only occurs when `useScope: 'global'` in `useI18n` is specified.
That is, with `const { locale } = useI18n()` I get `const locale: WritableComputedRef<string>`, while with `const { locale } = useI18n({ useScope: 'global' });` I get `const locale: WritableComputedRef<unknown>`.

**Comment by it-xtech-dev** [comment]
I'm using vue-i18n@9.2.2 and having issues with `global.locale` type. Type recognition says its a `string` while with `legacy: false` should be `ref<string>`:
![Zrzut ekranu 2022-08-30 o 19 26 23](https://user-images.githubusercontent.com/22835881/187505721-86bed374-2f88-4012-9a39-f56d6b8d2848.png)

**Comment by rfox12** [comment]
@kazupon I believe @timothymctim has laid out the scenario quite well.  Non-legacy users are having trouble getting `Locale` to type correctly to `WritableComputedRef<Locale>`

**Comment by kazupon** [comment]
sorry, I'm focusing on nuxtjs/i18n for v8 alpha release. please 

Type definitions in vue-i18n are really complex.
I’m not a full-time OSS yet, so it may take some time until I'm starting on this issue.

**Comment by mberrg** [comment]
I'm experiencing the same problem in 9.2.2 

 Any update on this?

**Comment by timothymctim** [comment]
I’m currently working around this issue by exporting the result of `createI18n` in a separate file and importing this in `main.ts` (where you create the app and call `app.use(i18n);`) and wherever I need access to the global i18n object. For example,
```ts
import i18n from 'path/to/file/calling/createI18n.ts';

function myFunctionNeedingTheGlobalI18nObject() {
  const { locale } = i18n.global;  // or anything else you need
  // rest of code
}
```
Here, `locale` now types as `const locale: WritableComputedRef<string>`.

**Comment by benlind** [comment]
I'm also encountering this issue. In my case I am trying to initialize another package's locale with this ref (FormKit), but TypeScript is complaining that locale is actually a string:

> Argument of type 'string' is not assignable to parameter of type 'Ref<string>'.

**Comment by Narkoleptika** [comment]
I also ran into this issue while trying to define types using `createI18n<>`. I was already passing `legacy: false` and that was working ok, but as soon as I added the type definition in the brackets `<>`, it started throwing type errors. Turns out you also need to pass the legacy option as part of the type definition.

Using the example from the docs

```ts
const i18n = createI18n<[MessageSchema], 'en-US' | 'ja-JP', false>({
  legacy: false,
  locale: 'en-US',
  messages: {
    'en-US': enUS
  }
})

```

Notice the `false` after `'en-US' | 'ja-JP'`

Adding that fixed the issue for me.

**Comment by ibrahimBeladi** [comment]
Even with passing that legacy is false in the types parameters/arguments, the Locale is still string in the template
I am on v9.13.1

![image](https://github.com/intlify/vue-i18n/assets/11488356/2151dc75-8bab-4623-bf31-17756e3911d2)
![image](https://github.com/intlify/vue-i18n/assets/11488356/c84bdd87-5183-4065-9e47-18e6404ab846)

**Comment by schw4rzlicht** [comment]
Any update on this? I think I ran into the same issue. After upgrading from 9.2.2 to 9.14.x, typescript complains:

```
src/store/index.ts:63:13 - error TS2322: Type 'string' is not assignable to type '"en"'.

63             i18n.global.locale.value = locale;
```

**Comment by kazupon** [comment]
Thank you for the report and everyone who shared workarounds!

In v12 (still alpha), the Legacy API (`legacy: true`) has been completely removed. `i18n.global` now always returns a Composer instance, so `locale` is always `WritableComputedRef<string>`:

```ts
const i18n = createI18n({
  locale: 'en',
  messages: { ... }
})

// v12: always WritableComputedRef<string>
i18n.global.locale.value = 'ja'  // ✅ No type error
```

The type ambiguity between `string` (Legacy) and `WritableComputedRef<string>` (Composition) no longer exists in v12.

If you are on v9/v11, the workaround is to pass `false` as the type parameter:

```ts
const i18n = createI18n<false>({
  legacy: false,
  locale: 'en',
  messages: { ... }
})
```

Closing this as fixed in v12.
Thanks!
