### ISSUE TITLE
vue-i18n does not work with Typescript 5

### ISSUE THREAD

**Issue by DerZade** [intlify/vue-i18n-next#1415]
### Reporting a bug?

Version 9.2.2 does not work with typescript 5.0.4

```ts
error TS7016: Could not find a declaration file for module 'vue-i18n'. '<PROJECT_DIR>/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '<PROJECT_DIR>/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

31 import { useI18n } from 'vue-i18n';
                           ~~~~~~~~~~
```

### Expected behavior

I expect it not to error 😅 

### Reproduction

The following is simply a project created with `npm create vue@latest` with all options set to _"No"_, except Typescript. 

https://github.com/DerZade/vue-i18n-bug-report

### System Info

```shell
├── typescript@5.0.4
├── vite@4.3.9
├── vue-i18n@9.2.2
└── vue@3.3.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by DerZade** [comment]
There is already a issue in the old repository (https://github.com/kazupon/vue-i18n/issues/1670), but I took the liberty of opening a new one in the correct repo.

**Comment by kazupon** [comment]
As I commented on this issue vue-i18n v9.3 will fix that issue.
https://github.com/intlify/vue-i18n-next/issues/1327#issuecomment-1539491735

If you will avoid this issue, I would recommend installing the next tag version, (i.e. vue-i18n v9.3).
Currently in beta, this version has not changed much in terms of functionality from v9.2. Actually, It's used in nuxt i18n v8 beta.

close this issue, so duplicate.
Thanks!

**Comment by Bauxitedev** [comment]
For future reference, if anyone runs into this issue even when upgrading to the 9.3 beta, you need to upgrade to version `9.3.0-beta.19`, not `9.3.0-beta.11`.

**Comment by xieyezi** [comment]
thanks 

> For future reference, if anyone runs into this issue even when upgrading to the 9.3 beta, you need to upgrade to version `9.3.0-beta.19`, not `9.3.0-beta.11`.
