### ISSUE TITLE
global $t show issue 

### ISSUE THREAD

**Issue by JonDelWeb** [intlify/vue-i18n-next#1403]
### Reporting a bug?

The global variable "$t" show issue 'Property '$t' does not exist on type' in vue template

My ./i18n/index.ts files : 
`
import { createI18n } from 'vue-i18n';

import fr from "./locales/fr.json";
type MessageSchema = typeof fr

export default createI18n<[MessageSchema], 'fr'>({

  locale: import.meta.env.VITE_DEFAULT_LOCALE,
  fallbackLocale: import.meta.env.VITE_FALLBACK_LOCALE,
  legacy: false,
  messages: {
    'fr': fr,
  },
})  
`

My main.ts file : 
`
import { createApp } from 'vue';
import { createPinia } from 'pinia';

import i18n from "./i18n";

import App from './App.vue';
import router from './router';

import './index.css';

const app = createApp(App)

app.use(i18n)
app.use(createPinia())
app.use(router)

app.mount('#app')
`

My template file : 
`
<nav class="flex flex-row mx-2 m-0.5">
      <RouterLink class="px-1" to="login">{{  $t("auth.login") }}</RouterLink> /
       <RouterLink class="px-1" to="register">{{  $t("auth.register") }}</RouterLink>
</nav>
`

### Expected behavior

No issue :D

### Reproduction

1. create new vue3 project
2. install "vue-i18n": "^9.3.0-beta.17",
3. create json files
4. use $t in template

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 6.79 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 113.0.1
  npmPackages:
    @intlify/unplugin-vue-i18n: ^0.10.0 => 0.10.0 
    @vitejs/plugin-vue: ^4.2.1 => 4.2.2 
    @vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1 
    @vue/eslint-config-prettier: ^7.1.0 => 7.1.0 
    @vue/eslint-config-typescript: ^11.0.3 => 11.0.3 
    @vue/tsconfig: ^0.3.2 => 0.3.2 
    vite: ^4.3.4 => 4.3.5 
    vue: ^3.2.47 => 3.3.1 
    vue-i18n: ^9.3.0-beta.17 => 9.3.0-beta.14-77e850b 
    vue-moment: ^4.1.0 => 4.1.0 
    vue-router: ^4.1.6 => 4.2.0 
    vue-tsc: ^1.6.4 => 1.6.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by dodo1708** [comment]
I'm having the same issue.
Adding 
`"types": "./dist/vue-i18n.d.ts",`

to 

```
"exports": {
    ".": {
      "types": "./dist/vue-i18n.d.ts",
      "import": {
        "node": "./index.mjs",
        "default": "./dist/vue-i18n.esm-bundler.js"
      },
      "require": "./index.js"
    },
    "./dist/*": "./dist/*",
    "./index.mjs": "./index.mjs",
    "./package.json": "./package.json"
  },```

**Comment by g1eny0ung** [comment]
I have the same problem. The situation for me is that I upgrade `vue` to `v3.3` with pnpm, the old vue version seems to be confusing with the new, and running `pnpm dedupe` solves this problem.

**Comment by oikalyptus** [comment]
I have the same issue. `dedupe` won’t fix it for me.
I ran `patch-package` with @dodo1708 changes and it works.

**Comment by DominikWeickgenannt** [comment]
I was getting this error even with version 9.3.0-beta.17.
Deleting the node_modules & dist folders and rebuilding solved this for me.

**Comment by kazupon** [comment]
Thank you for your reporting!

Issue template said:
>Please provide a link to a repo that can reproduce the problem you ran into. A minimal reproduction is required (Why?). If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "Status: Need More Info" label. If no reproduction is provided after 5 days, it will be closed.

Could you give us your **minimal reproduction** with github repo or [stackbliz](https://stackblitz.com/) please? 🙏

**Comment by JonDelWeb** [comment]
No problem, I will try to do it this week-end... ;)

**Comment by mats852** [comment]
Hi @kazupon, I cannot share my repository, but I can provide further details, I have the same problem.

Here is the full error message

```
error TS7016: Could not find a declaration file for module 'vue-i18n'. '<redacted>/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '<redacted>/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.
```

**Comment by leighwilliams** [comment]
I ran in to this going from `9.2.2` to `9.3.0-beta-19`.

With `9.2.2` in node_modules/vue-i18n/dist/vue-i18n.d.ts there is:

```ts
declare module '@vue/runtime-core' {
    ...
    $t<
      Key extends string,
      DefinedLocaleMessage extends RemovedIndexResources<DefineLocaleMessage> = RemovedIndexResources<DefineLocaleMessage>,
      Keys = IsEmptyObject<DefinedLocaleMessage> extends false
        ? PickupPaths<{
            [K in keyof DefinedLocaleMessage]: DefinedLocaleMessage[K]
          }>
        : never,
      ResourceKeys extends Keys = IsNever<Keys> extends false ? Keys : never
    >(
      key: Key | ResourceKeys | Path
    ): TranslateResult
    ...
}
```

With `9.3.0-beta-19` there is no such section within node_modules/vue-i18n/dist/vue-i18n.d.ts. The entire `declare module '@vue/runtime-core' { ... }` is missing.

**Comment by oognuyh** [comment]
The same issue with 9.3.0-beta-19, so I downgraded to 9.3.0-beta-18.

**Comment by dkern** [comment]
@kazupon
I can also confirm that adding `types` to the package.json fixes the issue for me. v9.3.0-beta.19 is not working.

```json
  "exports": {
    ".": {
      "types": "./dist/vue-i18n.d.ts",
      // ...
  },
```

**Comment by dkern** [comment]
I was able to suppress this warning with a custom typescript definition. Therefore it's not needed to change the package.json in node_modules. Of course, this is not a real fix, but at least I can build the project again.

**i18n.d.ts:**
```typescript
export {};

declare module 'vue' {
  interface ComponentCustomProperties {
    $t: (key: string) => string;
    $tm: (key: string) => []|{[p: string]: any};
  }
}
```

If you use more/other function of i18n you may need to add the to the interface.

**Comment by gcharest** [comment]
It's probably just another workaround for the moment but I specifically referenced the types path and declared the vue-i18n module  in the env.d.ts file:

**env.d.ts**
```
/// <reference types="vite/client" /> 
/// <reference path="node_modules/vue-i18n/dist/vue-i18n.d.ts" />
declare module 'vue-i18n'
```

**Comment by bkis** [comment]
> I was able to suppress this warning with a custom typescript definition. Therefore it's not needed to change the package.json in node_modules. Of course, this is not a real fix, but at least I can build the project again.
> 
> **i18n.d.ts:**
> 
> ```ts
> export {};
> 
> declare module 'vue' {
>   interface ComponentCustomProperties {
>     $t: (key: string) => string;
>     $tm: (key: string) => []|{[p: string]: any};
>   }
> }
> ```

The problem with this is that it only fixes the most simple calls to `t`: Pass a string, get a string back. But there are a number of overloads, for example for passing key-value pairs for inserting values into the message like in `$t('admin.texts.levels.tipInsertLevel', { n: level + 1 })`.

I was able to also cover these by copying the type definition directly from `node_modules/vue-i18n/dist/vue-i18n.d.ts` (i'm on `9.3.0-beta.25`) and using them in way you suggested in `i18n.d.ts` in my project:

```ts
export {};

declare module 'vue' {
  interface ComponentCustomProperties {
    $t: ComposerTranslation<
      Messages,
      Locales,
      RemoveIndexSignature<{
        [K in keyof DefineLocaleMessage]: DefineLocaleMessage[K];
      }>
    >;
    $tm: Composition['tm'];
  }
}
```

Same thing you mentioned also applies here: If you are using other functions, you gotta add the type definitions for them. As I said, they can be found in `node_modules/vue-i18n/dist/vue-i18n.d.ts`. I am not very happy with having to work around this, but for the time being, it's okay.

**Comment by dkern** [comment]
@kazupon As this ticket is still on `need input` and you wanted an example, here you go:
https://stackblitz.com/edit/vitejs-vite-utp7nu?file=src%2FApp.vue

Now, as this is not an issue on the runtime but on type checking, execute the following command in the console to see the actual error:
`vue-tsc --noEmit --composite false`

You should get this response in console:

> src/App.vue:1:14 - error TS2339: Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 8 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (arg...'.
> 
> 1 <template>{{ $t('test') }}</template>
               ~~
> 
> 
> Found 1 error in src/App.vue:1

**Comment by kazupon** [comment]
@dkern 
Thank you your reprodution!

Your issue has fixed at v9.3.0, so if you would like to use, you can install v9.3.0-beta.25

**Comment by bkis** [comment]
@kazupon 
I am on `v9.3.0-beta.25` and I get

```
error TS2339: Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 8 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (arg...'
```

everywhere I use `$t` in my templates. I have set `legacy: false` and `globalInjection: true`. So I still need the [workaround I posted above](https://github.com/intlify/vue-i18n-next/issues/1403#issuecomment-1667538584) (modified workaround originally coming from @dkern) for it to work.

**Comment by dkern** [comment]
Thank you @kazupon. I've tested it in the example on stackbliz and it seems to work. But I'm not allowed to use beta channels in these projects, so I have to wait for the release. Is there any estimated time when 9.3 will be released?

@bkis I can't confirm that. In the example, when I install 9.3.0-beta.25 it doesn't throw any errors. Do you use any other command for type check?

**Comment by bkis** [comment]
@kazupon @dkern Sorry for the confusion. I had the dependency set to `"vue-i18n": "^9.3.0-beta.25"` and `npm update` didn't update from `beta.14` - I have no idea why. Pinning it to `9.3.0-beta.25` (without the caret) and updating actually pulled the correct version. And it *is in fact fixed*. Thanks!

**Comment by hugorabelo** [comment]
Hi, I'm using version `"vue-i18n": "^9.4.1"` and having a weird problem here. 
I can use this code in template and it works as well

`{{ $t('app.sidenav.currentObjectives') }}`

but inside the script of the same component I got an error `Cannot find name '$t'.ts(2304)` and I have to use this code to work and have to do it for each component

```
import  { useI18n } from 'vue-i18n'
const {t} = useI18n({})
```

How can I use a global variable $t inside scripts to not import useI18n for each component?

**Comment by bkis** [comment]
@hugorabelo I think `$t` only works in templates. The way you do it [seems to be the "official" way to access `t()` et al. in the script part of a component](https://vue-i18n.intlify.dev/guide/advanced/composition.html#global-scope).

**Comment by hugorabelo** [comment]
@bkis Thanks. I already read this document, but my question is: Am I always need to define this `const { t }` for each component I'm using translation in script?

**Comment by dkern** [comment]
> @bkis Thanks. I already read this document, but my question is: Am I always need to define this `const { t }` for each component I'm using translation in script?

Just create yourself a file where you configure your i18n plugin. There you can also do an export of the functions you frequently need to use. For example:

```js
import { createI18n } from 'vue-i18n';

const i18n = createI18n({ ... });
const { t, tm } = i18n.global;

export const $t = t;
export const $tm = tm;
```

And where ever you need them you can now just import the functions directly, like:

```js
import { $t } from './path/to/file';
$t('translate your message');
```

But of course, you always need to import them where you want to use it. You could make this variable also globally available in script if you prefer it that way: https://stackoverflow.com/a/65349231/6498658

**Comment by bkis** [comment]
> Just create yourself a file where you configure your i18n plugin. There you can also do an export of the functions you frequently need to use. For example:
> 
> ```js
> import { createI18n } from 'vue-i18n';
> 
> const i18n = createI18n({ ... });
> const { t, tm } = i18n.global;
> 
> export const $t = t;
> export const $tm = tm;
> ```

Nice, thanks. Could be a little more concise this way:

```ts
export const { t: $t, tm: $tm } = i18n.global;
```

**Comment by hugorabelo** [comment]
Thanks, everyone. I understood the idea. Also, I checked that global properties should be used only in Options API. For composition API, we should import everything. It's working now

**Comment by wassim-ben-amor** [comment]
Hello, I am using 
```
    "vue": "^3.3.4",
    "vue-i18n": "9.4.1",
```
But when using $t in the template, I have a ts error showing:
`Property '$t' does not exist on type '{ $: ComponentInternalInstance; ...`

I have checked that the installed package is exactly `v9.4.1`.
Doing a production build or run vite in a dev server compiles correctly without throwing error in the terminal and show correctly the translations.

Do you think I need to define the ComponentCustomProperties interface as mentioned in the answers ?
Thank you,

**Comment by Nick-Hopps** [comment]
have mentioned it in volar: https://github.com/vuejs/language-tools/issues/3735

![image](https://github.com/intlify/vue-i18n-next/assets/16911282/db4c3891-5ae7-42e2-bc3d-0e50b89899b3)

**Comment by Nick-Hopps** [comment]
> Hello, I am using
> 
> ```
>     "vue": "^3.3.4",
>     "vue-i18n": "9.4.1",
> ```
> 
> But when using $t in the template, I have a ts error showing: `Property '$t' does not exist on type '{ $: ComponentInternalInstance; ...`
> 
> I have checked that the installed package is exactly `v9.4.1`. Doing a production build or run vite in a dev server compiles correctly without throwing error in the terminal and show correctly the translations.
> 
> Do you think I need to define the ComponentCustomProperties interface as mentioned in the answers ? Is the `$t` still available in the templates after migrating to v9 ? Because in this [doc](https://vue-i18n.intlify.dev/guide/migration/vue3.html#setup-option) I see that we have the usage of `$t`.
> 
> Thank you,

try to remove old node_moduls and package-lock file and reinstall

**Comment by Nick-Hopps** [comment]
I have figured it out, it is because I have a monorepo installed with vue@3.2.47, the mian version I'm using is vue@3.3.4, and package '@vue/runtime-core' under root node_moudles belongs to 3.2.47 and 'vue/node_modules/@vue/runtime-core' is what 3.3.4 really using.

**Comment by ByScripts** [comment]
We're using Yarn Workspace.

Removing all `node_modules` directories then running `yarn install` fixed the problem (no need to remove `yarn.lock`).

**Comment by 0xDarker** [comment]
I'm facing the same issue with vue-i18n@9.9.1 and vue@3.4.15, `$t` cannot be recognized. 
While I downgrade to vue@3.3.4, it is OK.

**Comment by TheNoim** [comment]
> I'm facing the same issue with vue-i18n@9.9.1 and vue@3.4.15 in pnpm monorepo, `$t` cannot be recognized. While I downgrade to vue@3.3.4, it is OK.

Maybe this helps creating a patch:

In `dist/vue-i18n.d.ts` change the line `declare module '@vue/runtime-core' {` to `declare module 'vue' {`.

Like this:

![image](https://github.com/intlify/vue-i18n-next/assets/5133056/0ce41583-5d2f-4d20-b6f5-dd6d6bb64790)

This is btw also the way how the vue docs do augmentation: https://vuejs.org/api/utility-types.html#componentcustomproperties I don't know whether there is a reason why it is like this or not. 

For the time being I just created a local patch.

**Comment by throrin19** [comment]
Any simple way to fix this problem ?

**Comment by jmzwcn** [comment]
> > I'm facing the same issue with vue-i18n@9.9.1 and vue@3.4.15 in pnpm monorepo, `$t` cannot be recognized. While I downgrade to vue@3.3.4, it is OK.
> 
> Maybe this helps creating a patch:
> 
> In `dist/vue-i18n.d.ts` change the line `declare module '@vue/runtime-core' {` to `declare module 'vue' {`.
> 
> Like this:
> 
> ![image](https://private-user-images.githubusercontent.com/5133056/330739959-0ce41583-5d2f-4d20-b6f5-dd6d6bb64790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTk5NzQsIm5iZiI6MTcyNjc5OTY3NCwicGF0aCI6Ii81MTMzMDU2LzMzMDczOTk1OS0wY2U0MTU4My01ZDJmLTRkMjAtYjZmNS1kZDZkNmJiNjQ3OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMDIzNDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjViZTkwNjVhZDk1MjlhZDE5N2NiZDAxNWY1N2E0ZmYyZDQwZjk5NWMzMTgzMTgwZDIwM2JmNWY3YWU4MWJiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yXUwD6Ut1iJPCxdg2KMI74FRg6RUQVFvqmgzL-KciR4)
> 
> This is btw also the way how the vue docs do augmentation: https://vuejs.org/api/utility-types.html#componentcustomproperties I don't know whether there is a reason why it is like this or not.
> 
> For the time being I just created a local patch.

Fix is here.

**Comment by bkis** [comment]
> > Just create yourself a file where you configure your i18n plugin. There you can also do an export of the functions you frequently need to use. For example:
> > ```js
> > import { createI18n } from 'vue-i18n';
> > 
> > const i18n = createI18n({ ... });
> > const { t, tm } = i18n.global;
> > 
> > export const $t = t;
> > export const $tm = tm;
> > ```
> 
> Nice, thanks. Could be a little more concise this way:
> 
> ```ts
> export const { t: $t, tm: $tm } = i18n.global;
> ```

Regarding the above approach: Did anyone try to make this work with TypeScript `>=5.6.0`? Because as soon as I upgrade TS to `5.6.x` it starts complaining. If I remove the export, there are no errors. But with

```ts
export const i18n = createI18n(i18nOptions);
export const { t: $t, te: $te, tm: $tm } = i18n.global;
```

TS starts complaining:

```
The inferred type of '$t' cannot be named without a reference to 'vue-i18n/node_modules/@intlify/core-base'. This is likely not portable. A type annotation is necessary.ts(2742)
```

Same for `$tm`, but not for `$te`.

**Comment by Soviut** [comment]
What's strange is I'm specifically seeing this error in VSCode but not when I run a type check.

```
Property '$t' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<...>
```

I'm using `@intlify/unplugin-vue-i18n` with Vite but I'm not sure that would be affecting the types within vue.

**Comment by morrowcreative** [comment]
This is still a problem, also in v10.0.4. Any update please?

**Comment by Soviut** [comment]
My issue with it happening in VSCode was solved by

- deleting `package-lock.json`
- `rm -rf node_modules`
- doing a fresh `npm install`

This has worked on several repos with the same issue in VSCode.

**Comment by maximemoreillon** [comment]
Having the same issue since updating my packages: 

```
"typescript": "^5.6.3",
"vite": "^5.3.4",
"vue-tsc": "^2.0.26"
```

**Comment by ntsphwoelfel** [comment]
I also have this problem now after upgrading my dependencies
```
    "@intlify/eslint-plugin-vue-i18n": "^3.0.0",
    "@openapitools/openapi-generator-cli": "^2.14.1",
    "@stylistic/eslint-plugin": "^2.9.0",
    "@stylistic/eslint-plugin-js": "^2.9.0",
    "@types/lodash-es": "^4.17.12",
    "@types/node": "^20.16.15",
    "@vitejs/plugin-vue": "^5.1.4",
    "@vue/eslint-config-typescript": "^13.0.0",
    "eslint": "^8.57.1",
    "eslint-config-standard": "^17.1.0",
    "eslint-plugin-import": "^2.31.0",
    "eslint-plugin-n": "^16.6.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^6.6.0",
    "eslint-plugin-vue": "^9.29.1",
    "eslint-plugin-vuetify": "^2.4.0",
    "typescript": "^5.6.3",
    "vite": "^5.4.10",
    "vue-tsc": "^2.1.6"
```
Those should be the relevant dependencies, I can post all the dependencies if required.

**Comment by andersnm** [comment]
> Thanks, everyone. I understood the idea. Also, I checked that global properties should be used only in Options API. For composition API, we should import everything. It's working now

@hugorabelo Do you have any sources for this practise?

Because I am encountering this issue too with latest vue and i18n, and importing the $t seems the cleanest. But I'd like to know if $t without import should of worked somehow

**Comment by throrin19** [comment]
The problem is already here in v10. Despite we have `globalInjection: true`.

**Comment by BobbieGoede** [comment]
Please provide a minimal reproduction so we can help investigate your issue 🙏

**Comment by LouisLP** [comment]
Getting the same sort of problem. 

```
Property '$t' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<{}, { close: (...args: any[]) => void; notApplied: (...args: any[]) => void; applied: (...args: any[]) => void; expired: (...args: any[]) => void; }>, { OhVueIcon: typeof OhVueIcon; ... 6 more ...; handleExpired: typeof handleExpired; }, ... 23 more ..., {}>'.ts-plugin(2339)
```

Relevant versions are:

```
"vue": "^3.4.30"
"vue-i18n": "9.14.2"
"typescript": "~5.4.2"
"vue-tsc": "^2.1.6"
"@vue/tsconfig": "^0.5.1"
```

Manually setting `"vue-i18n": "9.14.2"` to `"vue-i18n": "9.10.2"` fixes it, but we're upgrading to fix vulnerabilities, so we're just manually downgrading during local development, and then switching it back.

**Comment by sydinh** [comment]
> What's strange is I'm specifically seeing this error in VSCode but not when I run a type check.
> 
> ```
> Property '$t' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<...>
> ```
> 
> I'm using `@intlify/unplugin-vue-i18n` with Vite but I'm not sure that would be affecting the types within vue.

@Soviut Soviut It could be from your type-checking setup. I'm facing both 😞

**Comment by jotolo** [comment]
Same happening here!

**Comment by GarlandQian** [comment]
11.1.1 still has this bug

**Comment by johnsvanda** [comment]
Same here

**Comment by 2234839** [comment]
> I have the same problem. The situation for me is that I upgrade `vue` to `v3.3` with pnpm, the package with the old vue version seems to be confusing with the new one, and running `pnpm dedupe` solves this problem.

This works for me, thanks

**Comment by johnsvanda** [comment]
@2234839 That didn't solved for me :/

**Comment by triopter** [comment]
I was experiencing the exact same error as @sydinh while working on upgrading some dependencies.  After a bit of bisection, I've tracked down the version where it begins to occur to v9.14.0 in PR #1919 .  And after a heck of a lot more futzing with dependencies, I tracked down the cause to an older version of `vue-router`.  After unpinning it from v4.1.6 (letting it upgrade to v4.5.0), the error resolves.

**Comment by Narretz** [comment]
For me, this is caused by https://github.com/intlify/vue-i18n/pull/1888

https://github.com/intlify/vue-i18n/commit/c18144dad7edd59af59846855c441efdd0bbcd3b

`declare module '@vue/runtime-core' {`

was changed to

`declare module 'vue' {`

and now my LSP-typescript doesn't recognize this.$t anymore

Maybe I'll just patch it in the node_modules folder

**Comment by Narretz** [comment]
Ok, so this happens when other packages augment @vue/runtime-core instead of vue. For me,this was my own app, vue-router, and vue/apollo-option. Both packages latest versions have changed the augmentation.

**Comment by LuoShiXi** [comment]
Same here(In WebStorm):
    "vue": "^3.5.13",
    "vue-i18n": "^11.1.2",

and I found out through one of my old projects that its vue and i18n versions are ok, configured as follows:
    "vue": "3.4.21",
    "vue-i18n": "9.10.2",

You can use the old version first if you want, and I've found that the vue and vue-i18n versions need to match.

![Image](https://github.com/user-attachments/assets/ce0bbbae-337e-45a7-83f4-486f445a374f)

**Comment by triopter** [comment]
>  I've found that the vue and vue-i18n versions need to match

@LuoShiXi -- what do you mean by this, and where can one go to find what versions match one another?

**Comment by LuoShiXi** [comment]
> > I've found that the vue and vue-i18n versions need to match
> 
> [@LuoShiXi](https://github.com/LuoShiXi) -- what do you mean by this, and where can one go to find what versions match one another?

Sorry, I didn't find it somewhere, it's a combination I got from my own local experiments, and whether other combinations can be verified has not yet been verified

**Comment by stoychod** [comment]
>Ok, so this happens when other packages augment `@vue/runtime-core` instead of `vue`. For me,this was my own app, `vue-router`, and  `vue/apollo-option`. Both packages latest versions have changed the augmentation.

Same here! For me it was an older version of `@inertiajs/vue3` - 1.2.0. The problem was solved in version [v2.0.1](https://github.com/inertiajs/inertia/releases/tag/v2.0.1). 
To find the package causing the problem I decided to look for any file in my project mentioning the `ComponentCustomProperties` interface. So I ran `rg --hidden --no-ignore ComponentCustomProperties` in the root of my project and a few files came up but only the `/node_modules/@inertiajs/vue3/types/types.d.ts` used `@vue/runtime-core` instead of `vue`.

**Comment by 50Bytes-dev** [comment]
> I was experiencing the exact same error as [@sydinh](https://github.com/sydinh) while working on upgrading some dependencies. After a bit of bisection, I've tracked down the version where it begins to occur to v9.14.0 in PR [#1919](https://github.com/intlify/vue-i18n/pull/1919) . And after a heck of a lot more futzing with dependencies, I tracked down the cause to an older version of `vue-router`. After unpinning it from v4.1.6 (letting it upgrade to v4.5.0), the error resolves.

This works for me, thanks

**Comment by TiagoSilvaPereira** [comment]
Same issue here, using:

vue@3.5.16
@inertiajs/vue3@2.0.11
laravel-vue-i18n@2.8.0

**Comment by kazupon** [comment]
Thank you for all the reports and discussion!

This issue was fixed in v9.3.0 (specifically v9.3.0-beta.25). For most users, the root cause was either:

1. A missing `types` field in `package.json` exports (fixed in v9.3.0)
2. Duplicate Vue package versions in `node_modules` (resolved by `pnpm dedupe`, deleting `node_modules` and reinstalling, or pinning versions)

v9 has reached the end of its LTS support period. If you are still experiencing type issues, please upgrade to v11 or v12 (still alpha)

Closing this issue.

Thanks!
